config/routes.rb
Rails.application.routes.draw do
  root to: "top#index" 
  devise_for :users
  resources :books
  resources :top, only:[:index]
  resources :about, only:[:index]
  resources :users, only:[:index,:show,:edit,:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user

    validates :body, length: { maximum: 200 }, presence: true
    validates :title, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, length: { maximum: 20 }, length: { minimum: 2 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction, :profile_image_id])
    end

    def after_sign_in_path_for(resource)
        user_path(resource)
      end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    def index
        @books = Book.all.order("id DESC").includes(:user)
        @new_book = Book.new
        @user = cuurent_user
    end

    def show
        @book = Book.find(params[:id])
        @new_book = Book.new
        @user = @book.user
    end

    def create
        @book = Book.new(book_params)
        if @book.save
          redirect_to @book, notice: 'Book was successfully created'

        else
            render :index
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
          redirect_to @book, notice: 'Book was successfully created'

        else
            render :index
        end
    end

    def destroy
        @book = Book.find(params[:id])
        if @book.destroy
            redirect_to books_path
        else
            redirect_to :back 
        end
    end

    private
    def book_params
        params.require(:book).permit(:title,:body).merge(user_id: current_user.id)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index 
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users=User.all.order("id DESC")
        @new_book = Book.new
        @user = current_user
    end

    def show
        @user = User.find(params[:id])
        @new_book = Book.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if current_user
            if @user.update(user_params)
                redirect_to user_path(current_user) ,notice:"User was successfully updated"
            else
                render :index
            end
        end
    end

    private
    def user_params
        params.require(:user).permit(:name,:introduction,:image,:profile_image)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>
    welcome to
	<span class="glyphicon glyphicon-book"></span>
	<strong>Bookers</strong>
    !
</h1>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-6  col-md-offset-3">
    <h1>Editting Book</h1>
    <%= form_with model:@book, local:true do |f|%>
      <div class="field row mb-3">
	      <%= f.label :title, "Title" %>
        <%= f.text_field :title, class:"col-xs-12" %>
      </div>
      <div class="field row mb-3">
        <%= f.label :body, "Opinion" %>
        <%= f.text_area :body, class:"col-xs-12"%>
      </div>
      <div class="actions row mb-3">
        <%= f.submit 'Update Book' ,class: "btn btn-primary col-xs-12"%>
      </div>
      <%if @book.present? %>
        <% if @book.errors.any? %>
          <% @book.errors.full_messages.each do |message| %>
            <div class="field row">
              <p><%= message %> error</p>
            </div>
          <% end %>
        <% end %>  
      <% end %> 
    <% end %> 
  </div>
  <div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<div class="row">
  <div class="col-xs-3">
    <%=render partial: "layouts/user_info" %>
  </div>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%if @books.present? %>
          <% @books.each do |book| %>
            <tr>
              <td><a href="/users/#{<%= book.user.id %>}"><%= attachment_image_tag book.user, :profile_image, :fill, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" ,size:"40x40"%></a></td>
              <td><%= link_to "#{book.title}", book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <%=render partial: "layouts/user_info" %>
  </div>
  <div class="col-xs-9">
    <h2>Book Detail</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
        <tbody>
            <tr>
              <% if @book.present? %>
                <td><a href="/users/#{<%= @book.user.id %>}"><%= attachment_image_tag @book.user, :profile_image, :fill, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg",size:"40x40"%></a></td>
                <td><%= link_to "#{@book.title}", book_path(@book) %></td>
                <td><%= @book.body %></td>
                <% if @book.user_id == current_user.id %>
                  <td><%= link_to "Edit", edit_book_path(@book), class:"btn-sm btn-success" %></td>
                  <td><%= link_to "Destroy",book_path(@book),method: :delete ,class:"btn-sm btn-danger" %></td>
                <% end %>
              <% end %>
            </tr>
        </tbody>
    </table>
  </div>
</div>

app/views/layouts/_user_info.html.erb
<h2>User Info</h2>
<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg",size:"100x100" %>
<table class="table">
    <tbody>
        <tr></tr>
        <tr>
            <th>name</th>
            <th><%= @user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
        </tr>
    </tbody>
</table>
<div class="row">
    <%= link_to "", edit_user_path(current_user),class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
</div>
<h2>New Book</h2>
<%%>
<%= form_with model:@new_book, local:true do |f|%>
    <div class="field row">
	    <%= f.label :title, "Title" %><br />
        <%= f.text_field :title %>
    </div>
    <div class="field row">
        <%= f.label :body, "Opinion" %><br />
        <%= f.text_area :body %>
    </div>
    <div class="actions row">
        <%= f.submit 'Create Book' ,class: "btn btn-primary col-xs-12"%>
    </div>
    <%if @book.present? %>
        <% if @book.errors.any? %>
            <% @book.errors.full_messages.each do |message| %>
                <div class="field row">
                    <p><%= message %> error</p>
                </div>
            <% end %>
        <% end %>
    <% end %>  
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
	  <div class="container">
		  <nav class="nav navbar-nav navbar-left">
			  <span>Bookers</span>
		  </nav>
		  <nav>
			  <ul class="nav navbar-nav navbar-right">
				  <%if user_signed_in? %>
					  <li><%= link_to "Home", user_path(current_user) %></li>
					  <li><%= link_to "Users", users_path %></li>
					  <li><%= link_to "Books", books_path %></li>
					  <li><%= link_to "log out", destroy_user_session_path %></li>
				  <% else %>
					<li><%= link_to "Home", root_path ,class: "glyphicon glyphicon-home home" %></li>
					<li><%= link_to "About", "/about" ,class: "glyphicon glyphicon-user users" %></li>
					<li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
					<li><%= link_to "log in", new_user_session_path, class: "glyphicon glyphicon-log-in log-in" %></li>
				  <% end %>
			  </ul>
		    </nav>
	    </div>
    </header>
	<div class="body" style="margin-top:50px">
		<div class="container">
			<%= notice %>
    	<%= yield %>
		</div>
	</div>
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-xs-3 col-xs-offset-9">
					<p>CopyRight Infratop.inc</p>
				</div>
			</div>
		</div>
	</footer>
  </body>
</html>

app/views/top/index.html.erb
	<div class="row">
		<div class="top-message col-md-offset-3 col-md-6">
			<h1>
				welcome to
				<span class="glyphicon glyphicon-book">
					<strong>Bookers!</strong>
				</span>
			</h1>
			<p>
				In
				<span class="glyphicon glyphicon-book"></span>
				<strong>Bookers</strong>
				,
			</p>
			<p>you can share and exchange your opinions, impressions, and emotions</p>
			<p>about various books!</p>
			<div class="btn-wrapper">
				<div class="row">
					<p><%= link_to "log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%= link_to "sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>
		</div>
	</div>

app/views/users/edit.html.erb
<%= form_with model:@user, local:true do |f|%>
    <div class="field row">
	    <%= f.label :name, "name" %>
        <%= f.text_field :name, value:@user.name, class:"col-xs-12" %>
    </div>
    <div class="field row">
        <%= f.label :profile_image, "Image" %>
        <%= f.attachment_field :profile_image, class:"col-xs-12" %>
    </div>
    <div class="field row">
        <%= f.label :introduction, "Introduction" %>
        <%= f.text_area :introduction, class:"col-xs-12" %>
    </div>
    <div class="actions row">
        <%= f.submit 'Update User', class:"col-xs-12 btn btn-primary"%>
    </div>
    <%if @user.present? %>
        <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |message| %>
                <div class="field">
                    <p><%= message %> error</p>
                </div>
            <% end %>
        <% end %>  
    <% end %> 
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">
    <%=render partial: "layouts/user_info" %>
  </div>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%if @users.present? %>
          <%@users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" ,size:"40x40"%></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <%=render partial: "layouts/user_info" %>
  </div>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <%@user.present? %>
          <%@user.books.each do |book| %>
            <tr>
              <td><a href="/users/#{<%= book.user.id %>}"><%= attachment_image_tag book.user, :profile_image, :fill, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" ,size:"40x40"%></a></td>
              <td><%= book.title %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
</div>